import time
str1="core python"
print(str1)
print()
print(type(str1))
print()
print("---using possitive direction---")
print()
print(str1[0])
print(str1[1])
print(str1[2])
print(str1[3])
print("--------------")
print()
print("----using negative index----")
print(str1[-11])
print(str1[-10])
print(str1[-9])
print(str[-8])
print("-----------")
print()
print.sleep(2)
print("end of an application")