import time
from sys import argv
print(argv)
print()
print(type(argv))
print('...using indexing operator...')
print()
print(argv[0])
print(argv[1])
print(argv[2])
print(argv[3])
print()
print('..data types..')
print(type(argv[0]))
print(type(argv[1]))
print(type(argv[2]))
print(type(argv[3]))
print()
print(".......")
time.sleep(2)
print('end of an application')