import time
a=eval(input('enter any number of a:'))
b=eval(input('enter any number of b:'))
c=eval(input('enter any number of c:'))
print()
print('enter the decimal number')
res1=bin(a)
print('the binary number is:',res1)
print(res1)
print(type(res1))
print()
res2=oct(b)
print('the octal number is:',res2)
print(res2)
print(type(res2))
print()
res3=hex(c)
print('the hexa number is:',res3)
print(res3)
print(type(res3))
print()
time.sleep(2)
print('end of an application')