import time
pid=input('enter the pid:')
pname=input("enter the pname:")
pprice=input("enter the pprice:")
m_date=input ("enter the m_date:")
ex_date=input("enter the ex-date:")
print('...product information...')
print("pid is:",pid)
print("pname is:",pname)
print("pprice is:",pprice)
print("m_date:",m_date)
print("ex_date:",m_date)
print()
time.sleep(2)
print("end of application")