import time
x,y,z=20,5,30
print()
print('....information....')
print('...time...')
print(x,y,z,sep=":")
print()
print('...date...')
print(x,y,z,sep="/")
print()
print("digital time")
print(x,y,z,sep=":")
print()
print('amount in inr')
print(x,y,z,sep=",")
print()
time.sleep(2)
print('end of an application')