import time
l1=['A','B','C','D']
l2=['A','B','C','D']
print()
print("---List object---")
print(l1)
print()
print(l2)
print()
print("---Addresses---")
print(id(l1))
print()
print(id(l2))
print()
print()
print("---Using IO---")
print(l1 is l2)
print()
print(l1 is not l2)
print()
time.sleep(2)
print("End of an application ...")
