import time
l1=('A','B','C','D')
l2=(chr(30),chr(40),chr(50),chr(60))
print()
print(l1)
print(type(l1))
print()
print('...adderessing...')
print(id(l1))
print()
print(id(l2))
print(type(l2))
print(l2)
print()
print('...using identity operator...')
print(l1 is l2)
print()
print(l1 is not l2)
print()
time.sleep(2)
print('end of an application')