import time 
s1=set()
print(s1)
print("---Adding the objects---")
s1.add(1001)
s1.add("Mobile")
s1.add(17000)
s1.add('Samsung')
print(s1)
print()
print('---Removing the objects---')
s1.remove(1001)
s1.remove("Mobile")
s1.remove(17000)
print(s1)
print()
time.sleep(1)
print('End of an application ...')

