import time 
print("Core Python")
print()
print("Advance Python")
print()
print("Django with RestAPI")
print()
print(100//0)
print()
print("Oralce Database")
print()
print("MongoDB Database")
print()
time.sleep(2)
print("End of an application ..")